name: Add changeset from conventional commits

on:
  workflow_call:
    secrets:
      ECOSCRIPT_APP_ID:
        required: true
      ECOSCRIPT_APP_PRIVATE_KEY:
        required: true

concurrency: ${{ github.repository_owner_id }}-${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  run:
    if: github.repository_owner == 'portabletext'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.ECOSCRIPT_APP_ID }}
          private-key: ${{ secrets.ECOSCRIPT_APP_PRIVATE_KEY }}
      - uses: mscharley/dependency-changesets-action@688113f578e02cc37d62d3f5d11bb705744a802d # v1.2.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          use-conventional-commits: true
          sign-commits: true
